spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    sql:
      init:
        mode: always
    defer-datasource-initialization: true

server:
  port: 8080
